<!-- <script src="static/scripts/jquery-2.1.1.min.js"></script> -->
<!--<script src="static/v1/scripts/jquery-1.10.2.js"></script>-->
<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="static/v1/scripts/info.js"></script>
<!--<script src="static/v1/scripts/jquery.nicescroll.min.3.5.4.js"></script>-->
<script src="static/v1/scripts/theme.js"></script>
<script src="static/v1/scripts/util.js"></script>
<script src="static/v1/scripts/util/LockScreen.js"></script>
<script src="static/v1/scripts/util/normal.js"></script>
<script src="static/v1/scripts/util/page.js"></script>
<script src='static/v1/scripts/lang/<fmt:message key="system.js.lang"/>'></script>